# Generated by Django 3.1.6 on 2021-06-07 07:56

import auth_page.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('landmark', models.TextField(blank=True, null=True, verbose_name='Landmark')),
                ('street_address', models.TextField(verbose_name='Street Address')),
                ('city', models.CharField(max_length=40, verbose_name='City')),
                ('pin', models.CharField(max_length=6, verbose_name='PIN')),
                ('state', models.CharField(max_length=30, verbose_name='State')),
                ('country', models.CharField(max_length=30, verbose_name='Country')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to=auth_page.models.profilepic_directory_path, verbose_name='Profile Pic')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
