# Generated by Django 3.1.6 on 2021-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20210607_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified_user',
            field=models.BooleanField(default=False, verbose_name='Verfied User'),
        ),
    ]
