# Generated by Django 3.1.6 on 2021-06-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210618_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreview',
            name='highlight',
            field=models.BooleanField(default=False, verbose_name='Highlight this Review'),
        ),
    ]
