# Generated by Django 3.1.6 on 2021-07-01 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_company_companyaddress_companyemailhelpline_companyfounder_companytelephonehelpline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name_plural': 'Company address'},
        ),
        migrations.AlterModelOptions(
            name='companyemailhelpline',
            options={'verbose_name_plural': 'Company email helpline'},
        ),
        migrations.AlterModelOptions(
            name='companytelephonehelpline',
            options={'verbose_name_plural': 'Company telephone helpline'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='founded',
        ),
        migrations.AlterField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Company Status'),
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Company Fullname')),
                ('cin', models.CharField(max_length=100, verbose_name='CIN')),
                ('registration_number', models.CharField(max_length=20, verbose_name='Registration Number')),
                ('founded', models.DateTimeField(verbose_name='Founded In')),
                ('company_mode', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('joint', 'Joint')], max_length=20, verbose_name='Company Mode')),
                ('company_category', models.CharField(max_length=100, verbose_name='Company Category')),
                ('company_subcategory', models.CharField(max_length=100, verbose_name='Company Subcategory')),
                ('company_activity', models.TextField(verbose_name='Company Activity')),
                ('members', models.IntegerField(default=2, verbose_name='Company Members')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Company info',
            },
        ),
    ]
