# Generated by Django 3.1.6 on 2021-07-04 14:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_customerquery_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('answer', ckeditor.fields.RichTextField()),
                ('asked_date', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name_plural': 'Customer faq',
            },
        ),
    ]
